version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.prod
    container_name: dvholidays-client-prod
    networks:
      - dvholidays-nerwork

  nginx:
    image: nginx:1.15.12-alpine
    container_name: dvholidays-nginx-prod
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/dvholidays.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
    networks:
      - dvholidays-nerwork

networks:
  dvholidays-nerwork:
    driver: bridge
