version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    networks:
      - dvholidays
    volumes:
      - ./client:/app

networks:
  dvholidays:
