name: Check pull_request
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/cache@v3
      - uses: actions/setup-node@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - run: cd client && npm ci --force
      - run: cd client && npm run lint
      - run: cd client && npm run lint:types
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/cache@v3
      - uses: actions/setup-node@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - run: cd client && npm ci --force
      - run: cd client && npm run format:fix
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/cache@v3
      - uses: actions/setup-node@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - run: cd client && npm ci --force
      - run: cd client && npm run test
