name: Deploy to Test Server
on:
  push:
    branches: ["develop"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Isntall deps
        run: cd client && npm ci
      - name: Lint
        run: npm run lint
  format:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: cd client && npm ci
      - name: Format
        run: npm run format:fix
  build:
    needs: [lint, format]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying...
