name: Deploy to stage server
on:
  push:
    branches: ["stage"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Isntall deps
        run: cd client && npm ci --force
      - name: Lint
        run: cd client && npm run lint
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: cd client && npm ci --force
      - name: Format
        run: cd client && npm run format:fix
  stage:
    needs: [lint, format]
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    steps:
      - name: ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -a
